import {
  User,
  Facility,
  Equipment,
  FacilityEquipment,
  Booking,
  Conflict,
  Maintenance,
  SystemSettings,
  AuditLog,
  ResourceRequest
} from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  weights: {
    capacity: 0.25,
    equipment: 0.20,
    availability: 0.20,
    utilization: 0.15,
    preference: 0.10,
    demand: 0.10,
  },
  thresholds: {
    underutilized: 40,
    healthy: 80,
    high: 90,
    overDemanded: 90,
  },
};

export const INITIAL_EQUIPMENT: Equipment[] = [
  { id: 'eq-1', name: 'Projector' },
  { id: 'eq-2', name: 'Smart Board' },
  { id: 'eq-3', name: 'Computers' },
  { id: 'eq-4', name: 'Internet' },
  { id: 'eq-5', name: 'Air Conditioning' },
  { id: 'eq-6', name: 'Audio System' },
  { id: 'eq-7', name: 'Microphones' },
  { id: 'eq-8', name: 'Lab Equipment' },
  { id: 'eq-9', name: 'Power Outlets' },
  { id: 'eq-10', name: 'Video Conferencing' },
  { id: 'eq-11', name: 'Whiteboard' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Dr. Sarah Mitchell (Dean & Admin)',
    email: 'admin@campusiq.com',
    password_hash: 'password123',
    role: 'ADMIN',
    department: 'CSE',
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'usr-fac-1',
    name: 'Prof. Alan Vance',
    email: 'faculty@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'CSE',
    created_at: '2026-01-12T09:30:00Z',
    updated_at: '2026-01-12T09:30:00Z',
  },
  {
    id: 'usr-fac-2',
    name: 'Dr. Elena Rostova',
    email: 'elena.rostova@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'ECE',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'usr-fac-3',
    name: 'Prof. David Chen',
    email: 'david.chen@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'AI & DS',
    created_at: '2026-01-18T11:00:00Z',
    updated_at: '2026-01-18T11:00:00Z',
  },
  {
    id: 'usr-fac-4',
    name: 'Dr. Marcus Sterling',
    email: 'marcus.sterling@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'MECH',
    created_at: '2026-01-20T12:00:00Z',
    updated_at: '2026-01-20T12:00:00Z',
  },
  {
    id: 'usr-fac-5',
    name: 'Prof. Priya Sharma',
    email: 'priya.sharma@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'EEE',
    created_at: '2026-01-22T08:30:00Z',
    updated_at: '2026-01-22T08:30:00Z',
  },
  {
    id: 'usr-fac-6',
    name: 'Dr. Julian Thorne',
    email: 'julian.thorne@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'CIVIL',
    created_at: '2026-01-25T14:00:00Z',
    updated_at: '2026-01-25T14:00:00Z',
  },
  {
    id: 'usr-fac-7',
    name: 'Prof. Chloe Martin',
    email: 'chloe.martin@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'MBA',
    created_at: '2026-01-28T16:00:00Z',
    updated_at: '2026-01-28T16:00:00Z',
  },
  {
    id: 'usr-fac-8',
    name: 'Dr. Raymond Carver',
    email: 'raymond.carver@campusiq.com',
    password_hash: 'password123',
    role: 'FACULTY',
    department: 'SCIENCE',
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-02-01T09:00:00Z',
  },
  // Students
  {
    id: 'usr-stu-1',
    name: 'Alex Rivera',
    email: 'student@campusiq.com',
    password_hash: 'password123',
    role: 'STUDENT',
    department: 'CSE',
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-02-05T10:00:00Z',
  },
  ...Array.from({ length: 19 }, (_, i) => ({
    id: `usr-stu-${i + 2}`,
    name: `Student Researcher ${i + 2}`,
    email: `student${i + 2}@campusiq.com`,
    password_hash: 'password123',
    role: 'STUDENT' as const,
    department: (['CSE', 'ECE', 'AI & DS', 'MECH', 'EEE', 'CIVIL', 'MBA', 'SCIENCE'] as const)[i % 8],
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-02-05T10:00:00Z',
  })),
];

export const INITIAL_FACILITIES: Facility[] = [
  // Computer Labs
  {
    id: 'fac-cl-1',
    name: 'Computer Lab 1 (High Performance AI)',
    type: 'Computer Lab',
    capacity: 50,
    building: 'Turing Computing Center',
    floor: 2,
    room_number: 'TC-201',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Projector', 'Air Conditioning', 'Power Outlets'],
    current_utilization: 76,
    total_bookings_count: 32,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-2',
    name: 'Computer Lab 2 (Data Science Cluster)',
    type: 'Computer Lab',
    capacity: 45,
    building: 'Turing Computing Center',
    floor: 2,
    room_number: 'TC-202',
    status: 'OCCUPIED',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Projector', 'Air Conditioning', 'Smart Board'],
    current_utilization: 93, // Over-demanded!
    total_bookings_count: 48,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-3',
    name: 'Computer Lab 3 (Advanced Systems Lab)',
    type: 'Computer Lab',
    capacity: 60,
    building: 'Turing Computing Center',
    floor: 3,
    room_number: 'TC-301',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Projector', 'Air Conditioning', 'Power Outlets', 'Whiteboard'],
    current_utilization: 58, // Balanced!
    total_bookings_count: 24,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-4',
    name: 'Computer Lab 4 (Cloud Infrastructure)',
    type: 'Computer Lab',
    capacity: 75,
    building: 'Turing Computing Center',
    floor: 3,
    room_number: 'TC-302',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Projector', 'Air Conditioning', 'Audio System', 'Power Outlets'],
    current_utilization: 62,
    total_bookings_count: 27,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-5',
    name: 'Computer Lab 5 (Software Engineering)',
    type: 'Computer Lab',
    capacity: 40,
    building: 'Turing Computing Center',
    floor: 1,
    room_number: 'TC-101',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Projector', 'Whiteboard'],
    current_utilization: 68,
    total_bookings_count: 29,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-6',
    name: 'Computer Lab 6 (Cybersecurity Suite)',
    type: 'Computer Lab',
    capacity: 55,
    building: 'Turing Computing Center',
    floor: 4,
    room_number: 'TC-401',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Smart Board', 'Air Conditioning'],
    current_utilization: 70,
    total_bookings_count: 31,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-7',
    name: 'Computer Lab 7 (IoT & Embedded Sim)',
    type: 'Computer Lab',
    capacity: 48,
    building: 'Edison Technology Hall',
    floor: 2,
    room_number: 'ET-205',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Lab Equipment', 'Power Outlets'],
    current_utilization: 52,
    total_bookings_count: 20,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-cl-8',
    name: 'Computer Lab 8 (Multimedia & Graphics)',
    type: 'Computer Lab',
    capacity: 35,
    building: 'Arts & Media Wing',
    floor: 1,
    room_number: 'AM-104',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Projector', 'Smart Board', 'Air Conditioning'],
    current_utilization: 64,
    total_bookings_count: 22,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Classrooms (20 classrooms)
  ...Array.from({ length: 20 }, (_, i) => {
    const num = 101 + i;
    const block = i < 7 ? 'Block Alpha' : i < 14 ? 'Block Beta' : 'Block Gamma';
    const cap = i % 3 === 0 ? 60 : i % 3 === 1 ? 80 : 120;
    const util = 45 + ((i * 7) % 40);
    return {
      id: `fac-cr-${i + 1}`,
      name: `Classroom ${num} (${block})`,
      type: 'Classroom' as const,
      capacity: cap,
      building: block,
      floor: Math.floor(i / 6) + 1,
      room_number: `CR-${num}`,
      status: 'AVAILABLE' as const,
      utilization_threshold: 80,
      equipment: ['Projector', 'Whiteboard', 'Air Conditioning', 'Power Outlets', ...(i % 2 === 0 ? ['Audio System'] : [])],
      current_utilization: util,
      total_bookings_count: 15 + (i % 20),
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    };
  }),

  // Electronics Labs (6 labs)
  ...Array.from({ length: 6 }, (_, i) => ({
    id: `fac-el-${i + 1}`,
    name: `Electronics Lab ${i + 1} (VLSI & Circuitry)`,
    type: 'Electronics Lab' as const,
    capacity: 45 + (i * 5),
    building: 'Edison Technology Hall',
    floor: 3,
    room_number: `ET-30${i + 1}`,
    status: 'AVAILABLE' as const,
    utilization_threshold: 80,
    equipment: ['Lab Equipment', 'Power Outlets', 'Computers', 'Projector', 'Air Conditioning'],
    current_utilization: 60 + (i * 3),
    total_bookings_count: 22 + i,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  })),

  // Physics Labs (4 labs)
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `fac-pl-${i + 1}`,
    name: `Physics Lab ${i + 1} (Optics & Mechanics)`,
    type: 'Physics Lab' as const,
    capacity: 40,
    building: 'Newton Science Complex',
    floor: 1,
    room_number: `NS-10${i + 1}`,
    status: 'AVAILABLE' as const,
    utilization_threshold: 80,
    equipment: ['Lab Equipment', 'Power Outlets', 'Projector'],
    current_utilization: 54 + i * 4,
    total_bookings_count: 18 + i,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  })),

  // Chemistry Labs (4 labs)
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `fac-ch-${i + 1}`,
    name: `Chemistry Lab ${i + 1} (Analytical Chemistry)`,
    type: 'Chemistry Lab' as const,
    capacity: 35,
    building: 'Curie Science Complex',
    floor: 2,
    room_number: `CS-20${i + 1}`,
    status: 'AVAILABLE' as const,
    utilization_threshold: 80,
    equipment: ['Lab Equipment', 'Power Outlets', 'Whiteboard'],
    current_utilization: 48 + i * 5,
    total_bookings_count: 16 + i,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  })),

  // Seminar Halls (3 halls)
  {
    id: 'fac-sh-1',
    name: 'Seminar Hall 1 (Dr. APJ Abdul Kalam)',
    type: 'Seminar Hall',
    capacity: 180,
    building: 'Central Academic Block',
    floor: 1,
    room_number: 'CAB-100',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Projector', 'Audio System', 'Microphones', 'Air Conditioning', 'Video Conferencing', 'Internet'],
    current_utilization: 75,
    total_bookings_count: 36,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-sh-2',
    name: 'Seminar Hall 2 (Sir CV Raman)',
    type: 'Seminar Hall',
    capacity: 140,
    building: 'Central Academic Block',
    floor: 2,
    room_number: 'CAB-200',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Projector', 'Audio System', 'Microphones', 'Air Conditioning', 'Smart Board'],
    current_utilization: 68,
    total_bookings_count: 30,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-sh-3',
    name: 'Seminar Hall 3 (Homi Bhabha)',
    type: 'Seminar Hall',
    capacity: 220,
    building: 'Central Academic Block',
    floor: 3,
    room_number: 'CAB-300',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Projector', 'Audio System', 'Microphones', 'Air Conditioning', 'Video Conferencing', 'Smart Board'],
    current_utilization: 72,
    total_bookings_count: 34,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Auditoriums (2 auditoriums)
  {
    id: 'fac-aud-1',
    name: 'Grand University Auditorium',
    type: 'Auditorium',
    capacity: 850,
    building: 'University Convocation Center',
    floor: 1,
    room_number: 'UCC-Main',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Projector', 'Audio System', 'Microphones', 'Air Conditioning', 'Video Conferencing', 'Internet'],
    current_utilization: 42,
    total_bookings_count: 14,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-aud-2',
    name: 'Science & Tech Auditorium',
    type: 'Auditorium',
    capacity: 450,
    building: 'Newton Science Complex',
    floor: 1,
    room_number: 'NS-Aud',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Projector', 'Audio System', 'Microphones', 'Air Conditioning', 'Video Conferencing'],
    current_utilization: 51,
    total_bookings_count: 19,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Meeting Rooms (4 meeting rooms)
  {
    id: 'fac-mr-a',
    name: 'Executive Meeting Room A',
    type: 'Meeting Room',
    capacity: 20,
    building: 'Administrative Tower',
    floor: 4,
    room_number: 'AT-401',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Video Conferencing', 'Air Conditioning', 'Smart Board', 'Internet', 'Power Outlets'],
    current_utilization: 64,
    total_bookings_count: 28,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-mr-b',
    name: 'Meeting Room B (Faculty Lounge Wing)',
    type: 'Meeting Room',
    capacity: 15,
    building: 'Administrative Tower',
    floor: 2,
    room_number: 'AT-204',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Projector', 'Air Conditioning', 'Whiteboard'],
    current_utilization: 23, // Underutilized (<40%)!
    total_bookings_count: 8,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-mr-c',
    name: 'Conference Room C (Dean Suite)',
    type: 'Meeting Room',
    capacity: 30,
    building: 'Administrative Tower',
    floor: 5,
    room_number: 'AT-501',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Video Conferencing', 'Air Conditioning', 'Audio System', 'Internet', 'Microphones'],
    current_utilization: 70,
    total_bookings_count: 25,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-mr-d',
    name: 'Meeting Room D (Research Wing)',
    type: 'Meeting Room',
    capacity: 12,
    building: 'Library Complex',
    floor: 3,
    room_number: 'LIB-302',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Whiteboard', 'Air Conditioning', 'Power Outlets'],
    current_utilization: 31, // Underutilized!
    total_bookings_count: 11,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Project Rooms (3 rooms)
  {
    id: 'fac-pr-1',
    name: 'Innovation Project Room 101',
    type: 'Project Room',
    capacity: 25,
    building: 'Student Innovation Hub',
    floor: 1,
    room_number: 'SIH-101',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Computers', 'Internet', 'Smart Board', 'Power Outlets', 'Whiteboard'],
    current_utilization: 78,
    total_bookings_count: 35,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-pr-2',
    name: 'Robotics Project Room 102',
    type: 'Project Room',
    capacity: 20,
    building: 'Student Innovation Hub',
    floor: 1,
    room_number: 'SIH-102',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Lab Equipment', 'Power Outlets', 'Computers', 'Internet'],
    current_utilization: 69,
    total_bookings_count: 29,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-pr-3',
    name: 'Incubation Studio 103',
    type: 'Project Room',
    capacity: 30,
    building: 'Student Innovation Hub',
    floor: 2,
    room_number: 'SIH-201',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Video Conferencing', 'Internet', 'Whiteboard', 'Air Conditioning'],
    current_utilization: 61,
    total_bookings_count: 24,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Sports Facilities (3 facilities)
  {
    id: 'fac-sp-1',
    name: 'Indoor Badminton Arena',
    type: 'Sports Facility',
    capacity: 50,
    building: 'Sports Complex',
    floor: 1,
    room_number: 'SC-Arena1',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Air Conditioning', 'Audio System'],
    current_utilization: 56,
    total_bookings_count: 21,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-sp-2',
    name: 'Campus Basketball Stadium',
    type: 'Sports Facility',
    capacity: 200,
    building: 'Sports Complex',
    floor: 1,
    room_number: 'SC-Stadium',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Audio System', 'Power Outlets'],
    current_utilization: 49,
    total_bookings_count: 17,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'fac-sp-3',
    name: 'Athletic Fitness & Gym Center',
    type: 'Sports Facility',
    capacity: 60,
    building: 'Sports Complex',
    floor: 2,
    room_number: 'SC-Gym',
    status: 'AVAILABLE',
    utilization_threshold: 80,
    equipment: ['Air Conditioning', 'Audio System', 'Power Outlets'],
    current_utilization: 73,
    total_bookings_count: 33,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

// Helper to get formatted date string YYYY-MM-DD
export function getDateOffset(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
}

export function generateSeedBookings(): Booking[] {
  const today = getDateOffset(0);
  const tomorrow = getDateOffset(1);
  const yesterday = getDateOffset(-1);
  const twoDaysAgo = getDateOffset(-2);

  const bookings: Booking[] = [
    // SPECIFIC HACKATHON DEMO SCENARIO BOOKING:
    // Computer Lab 1 is booked tomorrow from 14:00 to 16:00 so it's NOT available for the test
    {
      id: 'bk-demo-cl1-occupied',
      facility_id: 'fac-cl-1',
      facility_name: 'Computer Lab 1 (High Performance AI)',
      facility_type: 'Computer Lab',
      user_id: 'usr-fac-2',
      user_name: 'Dr. Elena Rostova',
      user_role: 'FACULTY',
      department: 'ECE',
      date: tomorrow,
      start_time: '14:00',
      end_time: '16:00',
      purpose: 'Deep Learning FPGA Workshop',
      status: 'CONFIRMED',
      priority: 'HIGH',
      students_count: 48,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    // Computer Lab 2 has multiple bookings tomorrow giving it high demand
    {
      id: 'bk-cl2-morn',
      facility_id: 'fac-cl-2',
      facility_name: 'Computer Lab 2 (Data Science Cluster)',
      facility_type: 'Computer Lab',
      user_id: 'usr-fac-3',
      user_name: 'Prof. David Chen',
      user_role: 'FACULTY',
      department: 'AI & DS',
      date: tomorrow,
      start_time: '10:00',
      end_time: '13:00',
      purpose: 'Big Data Hadoop Analytics Practical',
      status: 'CONFIRMED',
      priority: 'HIGH',
      students_count: 44,
      created_at: '2026-03-01T11:00:00Z',
      updated_at: '2026-03-01T11:00:00Z',
    },
    {
      id: 'bk-cl2-aft',
      facility_id: 'fac-cl-2',
      facility_name: 'Computer Lab 2 (Data Science Cluster)',
      facility_type: 'Computer Lab',
      user_id: 'usr-fac-1',
      user_name: 'Prof. Alan Vance',
      user_role: 'FACULTY',
      department: 'CSE',
      date: tomorrow,
      start_time: '13:30',
      end_time: '16:30', // overlaps 14:00-16:00, making CL2 unavailable!
      purpose: 'Distributed Systems Evaluation',
      status: 'CONFIRMED',
      priority: 'HIGH',
      students_count: 45,
      created_at: '2026-03-01T12:00:00Z',
      updated_at: '2026-03-01T12:00:00Z',
    },

    // TODAY's bookings across facilities:
    {
      id: 'bk-today-1',
      facility_id: 'fac-sh-1',
      facility_name: 'Seminar Hall 1 (Dr. APJ Abdul Kalam)',
      facility_type: 'Seminar Hall',
      user_id: 'usr-fac-1',
      user_name: 'Prof. Alan Vance',
      user_role: 'FACULTY',
      department: 'CSE',
      date: today,
      start_time: '09:00',
      end_time: '12:00',
      purpose: 'Keynote: Next Gen Artificial Intelligence',
      status: 'CONFIRMED',
      priority: 'HIGH',
      students_count: 160,
      created_at: '2026-03-02T08:00:00Z',
      updated_at: '2026-03-02T08:00:00Z',
    },
    {
      id: 'bk-today-2',
      facility_id: 'fac-cr-1',
      facility_name: 'Classroom 101 (Block Alpha)',
      facility_type: 'Classroom',
      user_id: 'usr-fac-4',
      user_name: 'Dr. Marcus Sterling',
      user_role: 'FACULTY',
      department: 'MECH',
      date: today,
      start_time: '10:00',
      end_time: '11:30',
      purpose: 'Thermodynamics Lecture Session',
      status: 'CONFIRMED',
      priority: 'MEDIUM',
      students_count: 55,
      created_at: '2026-03-02T08:30:00Z',
      updated_at: '2026-03-02T08:30:00Z',
    },
    {
      id: 'bk-today-3',
      facility_id: 'fac-el-1',
      facility_name: 'Electronics Lab 1 (VLSI & Circuitry)',
      facility_type: 'Electronics Lab',
      user_id: 'usr-fac-2',
      user_name: 'Dr. Elena Rostova',
      user_role: 'FACULTY',
      department: 'ECE',
      date: today,
      start_time: '14:00',
      end_time: '17:00',
      purpose: 'Microcontroller Programming Lab',
      status: 'CONFIRMED',
      priority: 'HIGH',
      students_count: 42,
      created_at: '2026-03-02T09:00:00Z',
      updated_at: '2026-03-02T09:00:00Z',
    },
    {
      id: 'bk-today-4',
      facility_id: 'fac-cl-5',
      facility_name: 'Computer Lab 5 (Software Engineering)',
      facility_type: 'Computer Lab',
      user_id: 'usr-stu-1',
      user_name: 'Alex Rivera',
      user_role: 'STUDENT',
      department: 'CSE',
      date: today,
      start_time: '13:00',
      end_time: '15:00',
      purpose: 'Hackathon Practice Session',
      status: 'CONFIRMED',
      priority: 'MEDIUM',
      students_count: 30,
      created_at: '2026-03-02T09:30:00Z',
      updated_at: '2026-03-02T09:30:00Z',
    },
    {
      id: 'bk-today-5',
      facility_id: 'fac-aud-1',
      facility_name: 'Grand University Auditorium',
      facility_type: 'Auditorium',
      user_id: 'usr-admin-1',
      user_name: 'Dr. Sarah Mitchell (Dean & Admin)',
      user_role: 'ADMIN',
      department: 'CSE',
      date: today,
      start_time: '16:00',
      end_time: '18:30',
      purpose: 'University Annual Orientation',
      status: 'CONFIRMED',
      priority: 'URGENT',
      students_count: 750,
      created_at: '2026-03-02T07:00:00Z',
      updated_at: '2026-03-02T07:00:00Z',
    },

    // SEEDED CONFLICT 1: DOUBLE BOOKING OVERLAP in Seminar Hall 1 today
    {
      id: 'bk-conflict-1a',
      facility_id: 'fac-sh-1',
      facility_name: 'Seminar Hall 1 (Dr. APJ Abdul Kalam)',
      facility_type: 'Seminar Hall',
      user_id: 'usr-fac-1',
      user_name: 'Prof. Alan Vance',
      user_role: 'FACULTY',
      department: 'CSE',
      date: today,
      start_time: '13:00',
      end_time: '15:00',
      purpose: 'CSE Autonomous Robotics Symposium',
      status: 'CONFLICT',
      priority: 'HIGH',
      students_count: 140,
      created_at: '2026-03-02T10:00:00Z',
      updated_at: '2026-03-02T10:00:00Z',
    },
    {
      id: 'bk-conflict-1b',
      facility_id: 'fac-sh-1',
      facility_name: 'Seminar Hall 1 (Dr. APJ Abdul Kalam)',
      facility_type: 'Seminar Hall',
      user_id: 'usr-fac-2',
      user_name: 'Dr. Elena Rostova',
      user_role: 'FACULTY',
      department: 'ECE',
      date: today,
      start_time: '14:00',
      end_time: '16:00', // overlaps 14:00 - 15:00
      purpose: 'ECE Nanotechnology Industry Seminar',
      status: 'CONFLICT',
      priority: 'HIGH',
      students_count: 150,
      created_at: '2026-03-02T10:15:00Z',
      updated_at: '2026-03-02T10:15:00Z',
    },

    // SEEDED CONFLICT 2: Scheduling overlap in Conference Room C
    {
      id: 'bk-conflict-2a',
      facility_id: 'fac-mr-c',
      facility_name: 'Conference Room C (Dean Suite)',
      facility_type: 'Meeting Room',
      user_id: 'usr-fac-7',
      user_name: 'Prof. Chloe Martin',
      user_role: 'FACULTY',
      department: 'MBA',
      date: tomorrow,
      start_time: '11:00',
      end_time: '12:30',
      purpose: 'MBA Executive Board Review',
      status: 'CONFLICT',
      priority: 'HIGH',
      students_count: 22,
      created_at: '2026-03-02T11:00:00Z',
      updated_at: '2026-03-02T11:00:00Z',
    },
    {
      id: 'bk-conflict-2b',
      facility_id: 'fac-mr-c',
      facility_name: 'Conference Room C (Dean Suite)',
      facility_type: 'Meeting Room',
      user_id: 'usr-fac-5',
      user_name: 'Prof. Priya Sharma',
      user_role: 'FACULTY',
      department: 'EEE',
      date: tomorrow,
      start_time: '11:30',
      end_time: '13:00',
      purpose: 'Renewable Grid Committee Meeting',
      status: 'CONFLICT',
      priority: 'MEDIUM',
      students_count: 20,
      created_at: '2026-03-02T11:20:00Z',
      updated_at: '2026-03-02T11:20:00Z',
    },
  ];

  // Generate 95+ realistic past and upcoming bookings to reach 100+ total bookings
  const departments: ('ECE' | 'CSE' | 'EEE' | 'MECH' | 'CIVIL' | 'AI & DS' | 'MBA' | 'SCIENCE')[] = [
    'CSE', 'ECE', 'AI & DS', 'MECH', 'EEE', 'CIVIL', 'MBA', 'SCIENCE',
  ];

  const facultyUsers = INITIAL_USERS.filter((u) => u.role === 'FACULTY');
  const studentUsers = INITIAL_USERS.filter((u) => u.role === 'STUDENT');

  const timeslots = [
    { start: '08:30', end: '10:00' },
    { start: '10:15', end: '11:45' },
    { start: '12:00', end: '13:30' },
    { start: '14:00', end: '15:30' },
    { start: '15:45', end: '17:15' },
  ];

  let bookingCounter = 1;

  for (let dayOffset = -7; dayOffset <= 5; dayOffset++) {
    const targetDate = getDateOffset(dayOffset);
    // Don't clutter tomorrow afternoon for Computer Lab 3 & 4 so they are free for the demo!
    for (let fIdx = 0; fIdx < INITIAL_FACILITIES.length; fIdx += 3) {
      const facility = INITIAL_FACILITIES[fIdx];
      // Keep Computer Lab 3 completely free tomorrow 14:00-16:00
      if ((facility.id === 'fac-cl-3' || facility.id === 'fac-cl-4') && dayOffset === 1) {
        continue;
      }
      const slot = timeslots[(fIdx + Math.abs(dayOffset)) % timeslots.length];
      const user = (fIdx % 4 === 0)
        ? studentUsers[bookingCounter % studentUsers.length]
        : facultyUsers[bookingCounter % facultyUsers.length];

      bookings.push({
        id: `bk-hist-${bookingCounter++}`,
        facility_id: facility.id,
        facility_name: facility.name,
        facility_type: facility.type,
        user_id: user.id,
        user_name: user.name,
        user_role: user.role,
        department: departments[bookingCounter % departments.length],
        date: targetDate,
        start_time: slot.start,
        end_time: slot.end,
        purpose: `${facility.type} Regular Course Session & Practicals`,
        status: (bookingCounter % 15 === 0) ? 'PENDING' : 'CONFIRMED',
        priority: (bookingCounter % 5 === 0) ? 'HIGH' : 'MEDIUM',
        students_count: Math.min(facility.capacity - 5, 45),
        created_at: '2026-02-15T00:00:00Z',
        updated_at: '2026-02-15T00:00:00Z',
      });
    }
  }

  return bookings;
}

export const INITIAL_CONFLICTS: Conflict[] = [
  {
    id: 'conf-1',
    booking_a_id: 'bk-conflict-1a',
    booking_b_id: 'bk-conflict-1b',
    facility_id: 'fac-sh-1',
    facility_name: 'Seminar Hall 1 (Dr. APJ Abdul Kalam)',
    date: getDateOffset(0),
    time_range: '14:00 – 15:00 Overlap (13:00-15:00 vs 14:00-16:00)',
    conflict_type: 'Double Booking',
    severity: 'CRITICAL',
    status: 'OPEN',
    created_at: '2026-03-02T10:15:00Z',
  },
  {
    id: 'conf-2',
    booking_a_id: 'bk-conflict-2a',
    booking_b_id: 'bk-conflict-2b',
    facility_id: 'fac-mr-c',
    facility_name: 'Conference Room C (Dean Suite)',
    date: getDateOffset(1),
    time_range: '11:30 – 12:30 Overlap (11:00-12:30 vs 11:30-13:00)',
    conflict_type: 'Scheduling Overlap',
    severity: 'HIGH',
    status: 'OPEN',
    created_at: '2026-03-02T11:20:00Z',
  },
  {
    id: 'conf-3',
    booking_a_id: 'bk-today-3',
    facility_id: 'fac-el-1',
    facility_name: 'Electronics Lab 1 (VLSI & Circuitry)',
    date: getDateOffset(0),
    time_range: '14:00 – 17:00',
    conflict_type: 'Capacity Violation',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    resolution: 'Split students across Electronics Lab 1 and 2 to avoid density hazard.',
    created_at: '2026-03-01T15:00:00Z',
    resolved_at: '2026-03-02T08:00:00Z',
  },
];

export const INITIAL_MAINTENANCE: Maintenance[] = [
  {
    id: 'maint-1',
    facility_id: 'fac-cl-8',
    facility_name: 'Computer Lab 8 (Multimedia & Graphics)',
    start_date: getDateOffset(3),
    end_date: getDateOffset(4),
    reason: 'GPU workstation driver overhaul and firmware updates',
    status: 'SCHEDULED',
  },
  {
    id: 'maint-2',
    facility_id: 'fac-sh-2',
    facility_name: 'Seminar Hall 2 (Sir CV Raman)',
    start_date: getDateOffset(-2),
    end_date: getDateOffset(-1),
    reason: 'Acoustic baffle calibration and projector bulb replacement',
    status: 'COMPLETED',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    user_id: 'usr-admin-1',
    user_name: 'Dr. Sarah Mitchell',
    action: 'SETTINGS_UPDATE',
    entity_type: 'SETTINGS',
    entity_id: 'GLOBAL',
    details: 'Calibrated capacity fit weight to 0.25 and equipment match to 0.20.',
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'aud-2',
    user_id: 'usr-fac-1',
    user_name: 'Prof. Alan Vance',
    action: 'REQUEST_CREATED',
    entity_type: 'RESOURCE_REQUEST',
    entity_id: 'req-init-1',
    details: 'Requested Computer Lab 3 for 55 students with Projector and Internet.',
    created_at: '2026-03-01T11:30:00Z',
  },
  {
    id: 'aud-3',
    user_id: 'usr-admin-1',
    user_name: 'Dr. Sarah Mitchell',
    action: 'CONFLICT_DETECTED',
    entity_type: 'CONFLICT',
    entity_id: 'conf-1',
    details: 'Identified 60 min double booking collision on Seminar Hall 1.',
    created_at: '2026-03-02T10:15:00Z',
  },
];
